### ISSUE TITLE
起動すると落ちる

### ISSUE THREAD

**Issue by clarinet758** [clarinet758/Oekaki#1]
ログ
05-06 21:15:42.909 15821-15821/com.nowshika.oekaki D/AndroidRuntime: Shutting down VM
05-06 21:15:42.909 15821-15821/com.nowshika.oekaki E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.nowshika.oekaki, PID: 15821
                                                                     java.lang.RuntimeException: Unable to resume activity {com.nowshika.oekaki/com.nowshika.oekaki.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:135)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                                         at android.support.v7.internal.app.WindowDecorActionBar.getDecorToolbar(WindowDecorActionBar.java:248)
                                                                         at android.support.v7.internal.app.WindowDecorActionBar.init(WindowDecorActionBar.java:201)
                                                                         at android.support.v7.internal.app.WindowDecorActionBar.<init>(WindowDecorActionBar.java:176)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.createSupportActionBar(AppCompatDelegateImplV7.java:174)
                                                                         at android.support.v7.app.AppCompatDelegateImplBase.getSupportActionBar(AppCompatDelegateImplBase.java:92)
                                                                         at android.support.v7.app.AppCompatDelegateImplV7.onPostResume(AppCompatDelegateImplV7.java:229)
                                                                         at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:139)
                                                                         at android.app.Activity.performResume(Activity.java:6089)
                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:135) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
05-06 21:15:42.910 2248-4658/system_process W/ActivityManager:   Force finishing activity 1 com.nowshika.oekaki/.MainActivity
05-06 21:15:43.877 2248-4658/system_process W/art: Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.run() from WindowAnimator.java:124 waiters=0 for 140ms
05-06 21:15:43.991 2248-4658/system_process W/art: Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.run() from WindowAnimator.java:124 waiters=0 for 114ms
05-06 21:15:44.305 2248-4658/system_process W/art: Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.run() from WindowAnimator.java:124 waiters=0 for 104ms
05-06 21:15:44.909 2248-4658/system_process W/art: Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.run() from WindowAnimator.java:124 waiters=0 for 161ms
05-06 21:15:45.287 2248-4658/system_process W/art: Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.run() from WindowAnimator.java:124 waiters=0 for 132ms
05-06 21:15:45.434 2248-4658/system_process W/art: Long monitor contention event with owner method=void com.android.server.wm.WindowAnimator$1.run() from WindowAnimator.java:124 waiters=0 for 147ms
                                                   
                                                   [ 05-06 21:15:45.780  2248: 4658 D/         ]
                                                   HostConnection::get() New Host Connection established 0x7ff5004910c0, tid 4658
05-06 21:15:45.797 1157-1157/? E/EGL_emulation: tid 1157: eglCreateSyncKHR(1299): error 0x3004 (EGL_BAD_ATTRIBUTE)

**Comment by clarinet758** [comment]
MainActivity.javaの
supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
をコメントアウトで動くようになったので一旦解決扱いで
